### ISSUE TITLE
Using backCUSUM as monitoring of structural breaks for 'high' frequency

### ISSUE THREAD

**Issue by MislavSag** [ottosven/backCUSUM#1]
Hi, thanks for sharing codes with the community :).

I would like to try your backCUSUM algorithm on structural break detection for financial time series. I would like to hear your opinion on my approach:
1. For the beginning I have chosen 1-minute time frame so there are lots of observations (~ 25.000). I have applied backCUSUM on a rolling window of size 100 (the length of the window is the same as the length of the series in the paper) on the returns of the close price to make series stationary.
2. I extract the last value of the detector element and compare it to the boundary (or critical value?).
3. If the last detector value is higher than the boundary then there is a break and vice versa.

The problem is that I don't get any break on the whole sample.

I suppose I didn't get the intuition right?

**Comment by ottosven** [comment]
Hi MislavSag, I suppose that you want to test whether there is a break in the mean value of your returns (i.e. in the intercept of your regression), and you tried something like `BQ.test(y~1)` or `SBQ.test(y~1).` In this case it is not surprising that you find no structural breaks since the returns are mean stationary around zero, and this property will not change unless we have some extreme events on financial markets.

What you have to do is to check whether the detector statistic divided by the boundary function, i.e. `BQ.test(y~1)$detector/BQ.test(y~1)$boundary,` exceeds the critical value `BQ.test(y~1)$critical.value` at least once. Equivalently, you can use `BQ.test(y~1)$rejection` to check whether the test rejects at your significance level.

You have to compare the entire trajectory of the detector to the critical value and not only its last value. Also this test is not designed for a rolling window approach. If you want a real-time monitoring scheme, use the function `SBQ.mon.` Since you have 25000 observations, you can also try a much larger sample size than 100.

**Comment by MislavSag** [comment]
Hi Sven,

Thanks for feedback. I have several observations and questions:
1. You are right, I tried with volatility and it makes more sense because there are structural breaks in volatility from time to time. I can than try to use volatility for constructing alpha in some way.
2. I am confused about the second paragraph. Would like to know if we are int the changed regime in the current moment. If I at whole period, it is possible that detector was  high in the middle of sample (say 100 observations and than become lower at the end of the sample, that is window). Shouldn't I than look at detector[last] / boundary[last] and compare it to critical value?
3. Yes, I would like monitoring scheme. I tried with SBQ.mon, but got better results with BQ.test. Maybe I use SBQ.mon in wrong way.
4. I tried with larger sample (window) sized but I got better results with lower sizes (don't know why).
I will experiment with different window sizes and and methods (SBQ and BQ).

**Comment by ottosven** [comment]
The way you use the BQ test and its critical values is incorrect and the results are invalid. It is designed to test for a break in the entire sample and not in its last value.

What you may want to use is the SBQ monitoring. Choose a training sample of some size T that has no structural break (you may test that beforehand by BQ.test and SBQ.test). Your time series vector y must contain the training sample plus the new observation(s) for which you want to monitor (y is then of size greater than T). With SBQ.mon(y~1, T) you can run the monitoring scheme. Every time you have new data you can append them to your vector y and repeat the procedure.

In your case you may want to use the squared returns.

**Comment by MislavSag** [comment]
I believe you are right but I got the same or better results using only the last observation (vs using rejection boolean vector).

With SBQ, I get the worst results. I have used it in window too because it is not possible to use that many observations (too slow). 

Is it possible to somehow use new observation and estimate only new detectors etc for new observation for new observation. Something like monitoring. Now, I have to revaluate SBW every time. Now I use SBQ in a window of 400 with T = 300.

**Comment by ottosven** [comment]
I agree that the way the SBQ.mon function is implemented is not very efficient for high frequency data, since the whole history of the detector is computed every time you run the function, which takes quite a while for very large datasets. I try to provide a more efficient version for this case in the next release. Thanks for your feedback!

Please keep in mind that my asymptotic analysis and the resulting critical values from the paper are not valid for the procedure you propose. Your "better results" may just come from the fact that you have multiple testing, and thus your procedure will detect a break sooner or later with probability 1, even if there is no break.
